spring:
  application.name: healthmanager
  profiles.active: dev

app:
  name: "Health Manager API"
  version: "@project.version@"
  documentation: "/swagger-ui.html"
  repository: https://github.com/wesleybritovlk/health-manager

springdoc:
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
  api-docs:
    enabled: true
    path: /api/api-docs
