spring:
  config.import: optional:secrets-prod.yml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: validate
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:${H2_PATH}
    username: ${H2_USER}
    password: ${H2_PASS}
  h2.console:
    enabled: true
    path: /h2

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: info
