spring:
    config.import: optional:secrets.yml
    application.name: healthmanager
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource: 
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:${H2_PATH}
        username: sa
        password: 
    h2.console:
        enabled: true
        path: /h2
app:
    name: "Health Manager API"
    version: "@project.version@"
    documentation: "/swagger-ui.html"
    repository: https://github.com/wesleybritovlk/health-manager

springdoc:
    swagger-ui:
        enabled: true
        path: /api/swagger-ui.html
    api-docs:
        enabled: true
        path: /api/api-docs